### PR TITLE
wk1 day4 hw

### PR DESCRIPTION
**Pull request by derekw26**
_If you had no problems you can just leave it empty_

- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible)

7

- Was there anything that you struggled with?

credit card validator - took a while to come up with function for making sure all characters were numbers
The bank took 2 hrs - I ended up using too many nested ifs and for loops especially for the deposit, withdraw and transfer methods

- Is there any particular code you want me to look into?

bank - homework.js
don't know if I declared the object skeletons properly

- Is there anything that you'd like some further information on?

- Roughly how long did it take?
4 hrs

### CODE REVIEW

**Comment by derekw26** [comment]
Updated with MTA lab 
- difficulty 6
- struggled with defining cases for the trip types
- I only used arrays, would nested objects worked better here? especially if we need to expand the network in future
- took about 4hrs

**Comment by derekw26** [comment]
Updated with HTML labs - mostly completed Brooklyn, did some of Busy Hands, did not do Ecardly

- difficulty 9
- struggled with CSS and positioning of elements, also the hover effect on the navigation bar 
- around 4hrs

**Comment by patmifsud** [comment]
Hey Derek, sorry this one slipped thought the gaps here. 

> bank - homework.js
> don't know if I declared the object skeletons properly
Your bank function looks great. It took me a little while to get my head around it, but the way you incorporated the withdraw/ deposit functions into the objects themselves is a really cool approach. Very little I can suggest to improve here, I can see a couple of opportunities break some of the larger functions and series of if branches (e.g. 63-74, 92 - 110 - i left a comment) into smaller functions that you can call inside of the other methods, but probably down to personal preference or might not make sense in situ.

**Comment by patmifsud** [comment]
> [MTA lab](https://github.com/roweeena/seir48-homework/tree/c4b13e737c78b3dd16356fe891dbce9429f52098/Derek%20Wei/week_01/MTA) 
> I only used arrays, would nested objects worked better here? especially if we need to expand the network in future
Hey Derek, 
Looks great. I used arrays for my solution also, much easier to keep the stations in the correct order and iterate through them, but yeah - thats correct. The other advantage I guess is learning how to use [Object.keys()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)  to create an array of keys from an object, but you're using it elsewhere. No real suggestions here, code is polished, nice error handling (!). I guess maybe 176 - 201 could have had a little less repetition if you moved the code that logs stops and counts total nodes into a seperate function, but might not work in practice.

**Review by patmifsud — APPROVED** [review]

**Pull request merged**
